# Generated by Django 5.0.4 on 2024-05-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('number', models.IntegerField()),
                ('vaseID', models.CharField(blank=True, max_length=100, null=True)),
                ('fabric', models.CharField(max_length=100)),
                ('technique', models.CharField(blank=True, max_length=100, null=True)),
                ('painter', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('collection', models.CharField(blank=True, max_length=200, null=True)),
                ('provenance', models.CharField(blank=True, max_length=200, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('diameter', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('publications', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
